--Statement including a subquery:
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT 
FROM STUDENT 
WHERE DEPARTMENT = (SELECT DEPARTMENT FROM STUDENT WHERE STUDENT_ID = 2110213020);

--Statement including a JOIN:
SELECT s.FIRST_NAME, s.LAST_NAME, bi.ISSUE_DATE
FROM STUDENT s
INNER JOIN BOOK_ISSUE bi ON s.STUDENT_ID = bi.STUDENT_ID;

--Statement including a GROUP BY:
SELECT DEPARTMENT, COUNT(*) AS STUDENT_COUNT 
FROM STUDENT 
GROUP BY DEPARTMENT;

--Statement including a date function:
SELECT COUNT(*)
FROM BOOK_LOAN
WHERE EXTRACT(MONTH FROM ISSUE_DATE) = EXTRACT(MONTH FROM SYSDATE)
AND EXTRACT(YEAR FROM ISSUE_DATE) = EXTRACT(YEAR FROM SYSDATE);

--Statement including a character function:
SELECT UPPER(SUBSTR(FIRST_NAME, 1, 1)) AS FIRST_INITIAL, LAST_NAME
FROM STUDENT;

--Statement including an UPDATE:
UPDATE STUDENT
SET LAST_NAME = 'Doe'
WHERE FIRST_NAME = 'John';

--Statement including an ALTER TABLE;
ALTER TABLE STUDENT
ADD (ADMISSION_DATE DATE);


