
CREATE TABLE STUDENT (
    STUDENT_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    DEPARTMENT VARCHAR2(50)  NOT NULL,
    CLASS VARCHAR2(50) NOT NULL,
    PHONE_NUMBER VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(100),
    MAX_BOOKS NUMBER
);


CREATE TABLE FACULTY (
    FACULTY_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    DEPARTMENT VARCHAR2(50)  NOT NULL,
    PHONE_NUMBER VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(100),
    MAX_BOOKS NUMBER
);


CREATE TABLE AUTHOR (
    AUTHOR_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    BIRTH_DATE DATE,
    GENDER VARCHAR2(10)
);


CREATE TABLE PUBLISHER (
    PUBLISHER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    PHONE_NUMBER VARCHAR2(15)  NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL
);

CREATE TABLE BOOK (
    BOOK_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    PUBLICATION_YEAR NUMBER  NOT NULL,
    AUTHOR_ID NUMBER  NOT NULL,
    PAGE_COUNT NUMBER  NOT NULL,
    PUBLISHER_ID NUMBER  NOT NULL,
    CONSTRAINT FK_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (AUTHOR_ID),
    CONSTRAINT FK_BOOK_PUBLISHER FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (PUBLISHER_ID)
);


CREATE TABLE STAFF (
    STAFF_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    PHONE_NUMBER VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(100)  NOT NULL
);


CREATE TABLE BOOK_ISSUE (
    ISSUE_ID NUMBER PRIMARY KEY,
    BOOK_ID NUMBER  NOT NULL,
    USER_ID NUMBER  NOT NULL,
    ISSUE_DATE DATE  NOT NULL,
    RETURN_DATE DATE  NOT NULL,
    STAFF_ID NUMBER  NOT NULL,
    STATUS VARCHAR2(20),
    CONSTRAINT FK_ISSUE_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID),
    CONSTRAINT FK_ISSUE_STAFF FOREIGN KEY (STAFF_ID) REFERENCES STAFF (STAFF_ID)
);


CREATE TABLE FINE (
    FINE_ID NUMBER PRIMARY KEY,
    ISSUE_ID NUMBER  NOT NULL,
    USER_ID NUMBER  NOT NULL,
    DELAY_TIME NUMBER  NOT NULL,
    PENALTY_FEE NUMBER  NOT NULL,
    STAFF_ID NUMBER  NOT NULL,
    CONSTRAINT FK_FINE_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES BOOK_ISSUE (ISSUE_ID),
    CONSTRAINT FK_FINE_STAFF FOREIGN KEY (STAFF_ID) REFERENCES STAFF (STAFF_ID)
    
);
